version: '3'

services:
  superset:
      build:
        context: ./superset
        dockerfile: Dockerfile
      container_name: superset
      environment:
        - ADMIN_USERNAME=admin
        - ADMIN_EMAIL=admin@superset.com
        - ADMIN_PASSWORD=admin
      ports:
        - '8088:8088'
  drill:
    platform: linux/amd64
    image: apache/drill:latest
    ports:
      - "8047:8047"
    stdin_open: true